/* 
 * Sonda Saque e Pague
 *
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Objeto da requisição da sonda com informações da transação e do estabelecimento para a procura.
    /// </summary>
    [DataContract]
    public partial class SondaReq :  IEquatable<SondaReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SondaReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SondaReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SondaReq" /> class.
        /// </summary>
        /// <param name="infTransacao">infTransacao (required).</param>
        /// <param name="terminal">terminal (required).</param>
        public SondaReq(SondaReqInfTransacao infTransacao = default(SondaReqInfTransacao), SondaReqTerminal terminal = default(SondaReqTerminal))
        {
            // to ensure "infTransacao" is required (not null)
            if (infTransacao == null)
            {
                throw new InvalidDataException("infTransacao is a required property for SondaReq and cannot be null");
            }
            else
            {
                this.InfTransacao = infTransacao;
            }
            // to ensure "terminal" is required (not null)
            if (terminal == null)
            {
                throw new InvalidDataException("terminal is a required property for SondaReq and cannot be null");
            }
            else
            {
                this.Terminal = terminal;
            }
        }
        
        /// <summary>
        /// Gets or Sets InfTransacao
        /// </summary>
        [DataMember(Name="InfTransacao", EmitDefaultValue=false)]
        public SondaReqInfTransacao InfTransacao { get; set; }

        /// <summary>
        /// Gets or Sets Terminal
        /// </summary>
        [DataMember(Name="Terminal", EmitDefaultValue=false)]
        public SondaReqTerminal Terminal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SondaReq {\n");
            sb.Append("  InfTransacao: ").Append(InfTransacao).Append("\n");
            sb.Append("  Terminal: ").Append(Terminal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SondaReq);
        }

        /// <summary>
        /// Returns true if SondaReq instances are equal
        /// </summary>
        /// <param name="input">Instance of SondaReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SondaReq input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InfTransacao == input.InfTransacao ||
                    (this.InfTransacao != null &&
                    this.InfTransacao.Equals(input.InfTransacao))
                ) && 
                (
                    this.Terminal == input.Terminal ||
                    (this.Terminal != null &&
                    this.Terminal.Equals(input.Terminal))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InfTransacao != null)
                    hashCode = hashCode * 59 + this.InfTransacao.GetHashCode();
                if (this.Terminal != null)
                    hashCode = hashCode * 59 + this.Terminal.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
