/* 
 * Saque e Pague Sonda
 *
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1-sw2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SondaReqTransacao
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SondaReqTransacaoTests
    {
        // TODO uncomment below to declare an instance variable for SondaReqTransacao
        //private SondaReqTransacao instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SondaReqTransacao
            //instance = new SondaReqTransacao();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SondaReqTransacao
        /// </summary>
        [Test]
        public void SondaReqTransacaoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SondaReqTransacao
            //Assert.IsInstanceOfType<SondaReqTransacao> (instance, "variable 'instance' is a SondaReqTransacao");
        }


        /// <summary>
        /// Test the property 'DataLocal'
        /// </summary>
        [Test]
        public void DataLocalTest()
        {
            // TODO unit test for the property 'DataLocal'
        }
        /// <summary>
        /// Test the property 'HoraLocal'
        /// </summary>
        [Test]
        public void HoraLocalTest()
        {
            // TODO unit test for the property 'HoraLocal'
        }
        /// <summary>
        /// Test the property 'NsuSonda'
        /// </summary>
        [Test]
        public void NsuSondaTest()
        {
            // TODO unit test for the property 'NsuSonda'
        }
        /// <summary>
        /// Test the property 'NsuTransacao'
        /// </summary>
        [Test]
        public void NsuTransacaoTest()
        {
            // TODO unit test for the property 'NsuTransacao'
        }

    }

}
